apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  namespace: cst8918
  labels:
    app: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: ACR_PLACEHOLDER/weather-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather
                  key: api-key
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: weather
                  key: redis-host
            - name: REDIS_PORT
              value: "6379"
